package today.doingit.Server;

import java.nio.channels.SocketChannel;

/**
 * ResponseHandler will handle all outgoing messages.
 * These outgoing messages are passed on from the RequestHandler.
 * This message will be in JSON, and will have the scope of
 * users or user, that it should be sent to.
 *
 * It is only focused on who it should be sent to!
 */
public class ResponseHandler {
    /*
        Requests will have the following format,
        {
            "type":"responseType",
            "address":"ScopeOfUsers",
            "message":"message"
        }
     */

    /**
     * Sends a response generated by the RequestHandler, to the specified audience.
     * @param server the server object for performing Server function calls
     * @param client the client who sent the request (if any)
     * @param response the JSON response that is to be sent.
     * @return true if the message has been sent to the audience, or otherwise false.
     */
    public boolean handleResponse(Server server, SocketChannel client, String response) {
        return false;
    }
}
